### ISSUE TITLE
16 bit grayscale implementation

### ISSUE THREAD

**Issue by Martin-D31** [hpcn-uam/LOCO-ANS#2]
Hello, it's not really an issue in itself but I would like to know if an implementation for 16bits grayscale images are planned ?

**Comment by Tobi-Alonso** [comment]
Hi! Well, we did have an internal implementation for larger image depths, including 16 bit. As far as I remember, the ANS coder worked pretty well for those scenarios. However,  the context definition and adaptation mechanism required some adjusting/re-designing to improve its performance. We never got to do that, and it's not currently in the pipeline.
